declare module 'lucide-react' {
  import type { ForwardRefExoticComponent, RefAttributes, SVGProps } from 'react'

  export type LucideIcon = ForwardRefExoticComponent<
    Omit<SVGProps<SVGSVGElement>, 'ref'> & RefAttributes<SVGSVGElement>
  >

  export const AlertCircle: LucideIcon
  export const AlertTriangle: LucideIcon
  export const ArrowDown: LucideIcon
  export const ArrowLeftRight: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowUp: LucideIcon
  export const BadgePercent: LucideIcon
  export const BarChart3: LucideIcon
  export const Bell: LucideIcon
  export const BookOpen: LucideIcon
  export const Briefcase: LucideIcon
  export const Building: LucideIcon
  export const Building2: LucideIcon
  export const Calculator: LucideIcon
  export const Calendar: LucideIcon
  export const CalendarIcon: LucideIcon
  export const Check: LucideIcon
  export const CheckIcon: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const CheckCircleIcon: LucideIcon
  export const ChevronRightIcon: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronsUpDown: LucideIcon
  export const Circle: LucideIcon
  export const CircleHelp: LucideIcon
  export const CircleCheckIcon: LucideIcon
  export const CircleIcon: LucideIcon
  export const ClipboardList: LucideIcon
  export const Clock: LucideIcon
  export const ClockIcon: LucideIcon
  export const Cloud: LucideIcon
  export const CloudUpload: LucideIcon
  export const Coins: LucideIcon
  export const CoinsIcon: LucideIcon
  export const Cpu: LucideIcon
  export const CreditCard: LucideIcon
  export const Download: LucideIcon
  export const ExternalLink: LucideIcon
  export const Eye: LucideIcon
  export const EyeIcon: LucideIcon
  export const Factory: LucideIcon
  export const File: LucideIcon
  export const FileQuestion: LucideIcon
  export const FileSearch: LucideIcon
  export const FileSpreadsheet: LucideIcon
  export const FileText: LucideIcon
  export const FileTextIcon: LucideIcon
  export const FileUpIcon: LucideIcon
  export const GitCompare: LucideIcon
  export const Gauge: LucideIcon
  export const HelpCircle: LucideIcon
  export const InfoIcon: LucideIcon
  export const Infinity: LucideIcon
  export const Landmark: LucideIcon
  export const Layers: LucideIcon
  export const LayoutGrid: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const Library: LucideIcon
  export const Loader2: LucideIcon
  export const Loader2Icon: LucideIcon
  export const Lock: LucideIcon
  export const LockKeyhole: LucideIcon
  export const LogOut: LucideIcon
  export const Mail: LucideIcon
  export const MapPin: LucideIcon
  export const Maximize2: LucideIcon
  export const Menu: LucideIcon
  export const MessageCircle: LucideIcon
  export const Minus: LucideIcon
  export const Monitor: LucideIcon
  export const Moon: LucideIcon
  export const Newspaper: LucideIcon
  export const OctagonXIcon: LucideIcon
  export const Pencil: LucideIcon
  export const Plug: LucideIcon
  export const Plus: LucideIcon
  export const Receipt: LucideIcon
  export const RefreshCw: LucideIcon
  export const RotateCcw: LucideIcon
  export const Scale: LucideIcon
  export const ScanLine: LucideIcon
  export const Search: LucideIcon
  export const Shield: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldCheck: LucideIcon
  export const Sparkles: LucideIcon
  export const Star: LucideIcon
  export const Sun: LucideIcon
  export const Table: LucideIcon
  export const Trash2: LucideIcon
  export const Trash2Icon: LucideIcon
  export const Trophy: LucideIcon
  export const TriangleAlertIcon: LucideIcon
  export const Upload: LucideIcon
  export const User: LucideIcon
  export const Users: LucideIcon
  export const Workflow: LucideIcon
  export const X: LucideIcon
  export const XCircleIcon: LucideIcon
  export const XIcon: LucideIcon
}
