import { afterEach, describe, expect, it } from 'vitest'

import { createExtractionsRoutes } from '../routes/extractions'
import type { ExtractionRouteDependencies } from '../routes/extractions'
import type { ExtractionRecord } from '../repositories/extractions'
import { generateExportDocument } from '../workflows/export-workflow'
import { runExportWorkflow } from '../workflows/export-workflow'
import {
  configureExtractionsRepositoryDb,
} from '../repositories/extractions'
import type { DbPoolLike, DbQueryResult } from '../repositories/db'
import { routeTestEnv } from './route-test-helpers'
import { testApp, userAuthDependencies } from './task9-helpers'

class SequencePool implements DbPoolLike {
  constructor(private readonly rows: readonly unknown[]) {}

  async end(): Promise<void> {}

  async query<Row>(): Promise<DbQueryResult<Row>> {
    return { rows: this.rows as Row[] }
  }
}

const record: ExtractionRecord = {
  anonymousSessionId: null,
  confidenceScores: {},
  createdAt: '2026-06-12T00:00:00.000Z',
  deletedAt: null,
  documentFilename: 'lease.pdf',
  documentObjectKey: 'object-key',
  documentPageCount: 4,
  errorMessage: null,
  extractedData: {
    landlord_legal_name: { confidence: 0.9, source_text: 'ACME', value: 'ACME' },
  },
  id: '11111111-1111-4111-8111-111111111111',
  overallConfidence: 0.9,
  paymentStatus: 'paid',
  propertyType: 'retail',
  redFlags: [],
  showCamAudit: false,
  status: 'complete',
  updatedAt: '2026-06-12T00:00:00.000Z',
  userId: 'user-id',
}

function dependencies(
  overrides: Partial<ExtractionRouteDependencies> = {},
): ExtractionRouteDependencies {
  return {
    authDependencies: userAuthDependencies,
    deleteExtraction: () => Promise.resolve({ alreadyDeleted: false }),
    exportObjectExists: () => Promise.resolve(false),
    getExportObject: () => Promise.resolve(null),
    getExtraction: () => Promise.resolve(record),
    insertUpload: () => Promise.resolve(),
    listExtractions: () => Promise.resolve({ items: [], limit: 20, offset: 0, total: 0 }),
    putDocument: () => Promise.resolve('object-key'),
    startExportWorkflow: () => Promise.resolve(),
    startWorkflow: () => Promise.resolve(),
    validatePdf: () => Promise.resolve({ pageCount: 1 }),
    ...overrides,
  }
}

describe('export workflow and routes', () => {
  afterEach(() => {
    configureExtractionsRepositoryDb(null)
  })

  it('generates Worker-native DOCX, XLSX, and PDF bytes', async () => {
    const docx = generateExportDocument({
      format: 'docx',
      record: {
        ...record,
        extractedData: {
          list_field: { value: ['A', 'B'] },
          nested_field: { value: { name: 'nested' } },
          null_field: { value: null },
        },
      },
      template: 'commercial',
    })
    const xlsx = generateExportDocument({
      format: 'xlsx',
      record,
      template: 'commercial',
    })
    const pdf = generateExportDocument({
      format: 'pdf',
      record: {
        ...record,
        documentFilename: 'caf\u00e9\nlease.pdf',
      },
      template: 'commercial',
    })
    const pdfText = new TextDecoder().decode(pdf.bytes)

    expect(new TextDecoder().decode(docx.bytes.slice(0, 2))).toBe('PK')
    expect(new TextDecoder().decode(xlsx.bytes.slice(0, 2))).toBe('PK')
    expect(new TextDecoder().decode(pdf.bytes.slice(0, 8))).toBe('%PDF-1.4')
    expect(docx.contentType).toContain('wordprocessingml.document')
    expect(xlsx.contentType).toContain('spreadsheetml.sheet')
    expect(pdf.contentType).toBe('application/pdf')
    expect(pdfText).toContain('caf? lease.pdf')
    expect(pdfText.indexOf('xref')).toBe(Number(pdfText.match(/startxref\n(?<offset>\d+)/)?.groups?.offset))
  })

  it('runs export Workflow and uploads generated bytes to R2', async () => {
    configureExtractionsRepositoryDb(
      () =>
        new SequencePool([
          {
            ...record,
            anonymous_session_id: null,
            confidence_scores: {},
            created_at: record.createdAt,
            deleted_at: null,
            document_filename: record.documentFilename,
            document_object_key: record.documentObjectKey,
            document_page_count: record.documentPageCount,
            error_message: null,
            extracted_data: record.extractedData,
            id: record.id,
            overall_confidence: '0.9',
            payment_status: 'paid',
            property_type: record.propertyType,
            red_flags: [],
            show_camaudit: false,
            status: 'complete',
            updated_at: record.updatedAt,
            user_id: 'user-id',
          },
        ]),
    )
    const puts: { key: string; contentType?: string }[] = []
    const env = {
      ...routeTestEnv,
      DOCUMENTS_BUCKET: {
        delete: () => Promise.resolve(),
        get: () => Promise.resolve(null),
        list: () => Promise.resolve({ objects: [], truncated: false }),
        put: (key: string, _value: Uint8Array, options?: { httpMetadata?: { contentType?: string } }) => {
          const contentType = options?.httpMetadata?.contentType
          puts.push(
            contentType === undefined ? { key } : { contentType, key },
          )
          return Promise.resolve(null)
        },
      } as unknown as R2Bucket,
    }

    await expect(
      runExportWorkflow(
        {
          extractionId: record.id,
          format: 'docx',
          owner: { kind: 'user', userId: 'user-id' },
          taskId: 'task-id',
          template: 'commercial',
          version: 'v1',
        },
        {} as Parameters<typeof runExportWorkflow>[1],
        env,
      ),
    ).resolves.toMatchObject({ status: 'complete', taskId: 'task-id' })
    expect(puts[0]?.key).toContain('/exports/commercial-v1.docx')
  })

  it('dispatches export Workflow and returns a signed task id when cache misses', async () => {
    const starts: unknown[] = []
    const app = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(
        dependencies({
          startExportWorkflow: (input) => {
            starts.push(input)
            return Promise.resolve()
          },
        }),
      ),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )

    const response = await app.fetch(
      '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx',
      {
        body: JSON.stringify({ template: 'commercial' }),
        headers: { 'Content-Type': 'application/json' },
        method: 'POST',
      },
    )
    const body = (await response.json()) as { task_id: string; status: string; version: string }

    expect(response.status).toBe(202)
    expect(body.status).toBe('generating')
    expect(body.version).toBe('2026-06-12T00_00_00.000Z')
    expect(body.task_id).toContain('export:user:user-id:11111111-1111-4111-8111-111111111111:commercial:docx:')
    expect(starts).toEqual([
      {
        extractionId: record.id,
        format: 'docx',
        owner: { kind: 'user', userId: 'user-id' },
        taskId: body.task_id,
        template: 'commercial',
        version: body.version,
      },
    ])
  })

  it('returns cached export URL and streams export downloads through the API', async () => {
    const app = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(
        dependencies({
          exportObjectExists: () => Promise.resolve(true),
          getExportObject: () =>
            Promise.resolve({
              body: new ReadableStream({
                start(controller) {
                  controller.enqueue(new TextEncoder().encode('docx bytes'))
                  controller.close()
                },
              }),
              contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            }),
        }),
      ),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )

    const cached = await app.fetch(
      '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx',
      {
        body: JSON.stringify({ template: 'commercial' }),
        headers: { 'Content-Type': 'application/json' },
        method: 'POST',
      },
    )
    const download = await app.fetch(
      '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx/download?template=commercial&version=2026-06-12T00_00_00.000Z',
    )

    await expect(cached.json()).resolves.toMatchObject({
      format: 'docx',
      url: '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx/download?template=commercial&version=2026-06-12T00_00_00.000Z',
      version: '2026-06-12T00_00_00.000Z',
    })
    expect(download.status).toBe(200)
    expect(download.headers.get('Content-Disposition')).toContain('attachment')
    await expect(download.text()).resolves.toBe('docx bytes')
  })

  it('supports documented GET export generation for compatibility', async () => {
    const starts: unknown[] = []
    const app = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(
        dependencies({
          startExportWorkflow: (input) => {
            starts.push(input)
            return Promise.resolve()
          },
        }),
      ),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )

    const response = await app.fetch(
      '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/pdf?template=office',
      { headers: { 'Content-Type': 'application/json' } },
    )
    const body = (await response.json()) as { task_id: string; status: string }

    expect(response.status).toBe(202)
    expect(body.status).toBe('generating')
    expect(starts).toMatchObject([{ format: 'pdf', template: 'office' }])
  })

  it('streams cached PDF downloads through the API', async () => {
    const app = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(
        dependencies({
          getExportObject: () =>
            Promise.resolve({
              body: new ReadableStream({
                start(controller) {
                  controller.enqueue(new TextEncoder().encode('%PDF-1.4'))
                  controller.close()
                },
              }),
              contentType: 'application/pdf',
            }),
        }),
      ),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )

    const download = await app.fetch(
      '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/pdf/download?template=commercial&version=2026-06-12T00_00_00.000Z',
    )

    expect(download.status).toBe(200)
    expect(download.headers.get('Content-Type')).toBe('application/pdf')
    await expect(download.text()).resolves.toBe('%PDF-1.4')
  })

  it('rejects unsupported export formats', async () => {
    const app = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(dependencies()),
    )

    const csv = await app.fetch(
      '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/csv',
      { method: 'POST' },
    )

    expect(csv.status).toBe(400)
  })

  it('handles unpaid exports, missing workflow config, and missing downloads', async () => {
    const unpaid = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(
        dependencies({
          getExtraction: () => Promise.resolve({ ...record, paymentStatus: 'unpaid' }),
        }),
      ),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )
    const unconfiguredDependencies = dependencies()
    delete unconfiguredDependencies.startExportWorkflow
    const unconfigured = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(unconfiguredDependencies),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )
    const missingDownload = testApp(
      '/api/v1/extractions',
      createExtractionsRoutes(dependencies()),
      { ...routeTestEnv, TASK_SIGNING_SECRET: 'task-secret' },
    )

    expect(
      (
        await unpaid.fetch(
          '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx',
          { method: 'POST' },
        )
      ).status,
    ).toBe(403)
    expect(
      (
        await unconfigured.fetch(
          '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx',
          { method: 'POST' },
        )
      ).status,
    ).toBe(503)
    expect(
      (
        await missingDownload.fetch(
          '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/pdf/download',
        )
      ).status,
    ).toBe(404)
    expect(
      (
        await missingDownload.fetch(
          '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx/download',
        )
      ).status,
    ).toBe(404)
    expect(
      (
        await unpaid.fetch(
          '/api/v1/extractions/11111111-1111-4111-8111-111111111111/export/docx/download',
        )
      ).status,
    ).toBe(403)
  })
})
